import { getAllNotes } from "./useNotes";

// Opens a print-ready HTML page containing all the student's notes,
// then triggers window.print() so they can save it as PDF.
export function exportNotesAsPdf(studentId, courses) {
  const notes = getAllNotes(studentId);

  if (notes.length === 0) {
    alert("You haven't written any notes yet.");
    return;
  }

  // Group notes by courseSlug
  const byCourse = {};
  notes.forEach(({ courseSlug, moduleIndex, text }) => {
    if (!byCourse[courseSlug]) byCourse[courseSlug] = [];
    byCourse[courseSlug].push({ moduleIndex, text });
  });

  // Build HTML sections
  const sections = Object.entries(byCourse).map(([slug, moduleNotes]) => {
    const course = courses.find(c => c.slug === slug);
    const courseTitle = course ? course.title : slug;

    const noteItems = moduleNotes
      .sort((a, b) => a.moduleIndex - b.moduleIndex)
      .map(({ moduleIndex, text }) => {
        const mod = course?.modules?.[moduleIndex];
        const modTitle = mod ? mod.title : `Module ${moduleIndex + 1}`;
        const escaped = text.replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\n/g, "<br/>");
        return `
          <div class="note">
            <div class="mod-title">Module ${moduleIndex + 1}: ${modTitle}</div>
            <div class="note-text">${escaped}</div>
          </div>`;
      }).join("");

    return `
      <div class="course-section">
        <h2>${courseTitle}</h2>
        ${noteItems}
      </div>`;
  }).join("");

  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>My Notes — ModuloTrainer</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Fraunces:wght@600&family=IBM+Plex+Sans:wght@400;500;600&display=swap');
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:'IBM Plex Sans',sans-serif; color:#16241F; padding:48px; max-width:760px; margin:0 auto; }
  header { border-bottom:2px solid #D3DBD1; padding-bottom:16px; margin-bottom:32px; display:flex; justify-content:space-between; align-items:flex-end; }
  header h1 { font-family:'Fraunces',Georgia,serif; font-size:24px; font-weight:600; }
  header span { font-size:12px; color:#6E7D75; }
  .course-section { margin-bottom:36px; }
  .course-section h2 { font-family:'Fraunces',Georgia,serif; font-size:16px; color:#1F5138; border-left:3px solid #2F6F4E; padding-left:10px; margin-bottom:14px; }
  .note { background:#F8FAF6; border:1px solid #D3DBD1; border-radius:8px; padding:14px 16px; margin-bottom:10px; }
  .mod-title { font-size:11px; font-weight:600; color:#6E7D75; text-transform:uppercase; letter-spacing:.05em; margin-bottom:6px; }
  .note-text { font-size:13px; line-height:1.7; color:#3B4A44; }
  footer { margin-top:40px; border-top:1px solid #D3DBD1; padding-top:12px; font-size:11px; color:#6E7D75; text-align:center; }
  @media print { body { padding:24px; } }
</style>
</head>
<body>
<header>
  <div>
    <h1>My Study Notes</h1>
    <div style="font-size:12px;color:#6E7D75;margin-top:4px;">ModuloTrainer</div>
  </div>
  <span>Exported ${date}</span>
</header>
${sections}
<footer>Generated by ModuloTrainer · ${date}</footer>
<script>window.onload = () => window.print();</script>
</body>
</html>`;

  const blob = new Blob([html], { type: "text/html" });
  const url  = URL.createObjectURL(blob);
  window.open(url, "_blank");
  setTimeout(() => URL.revokeObjectURL(url), 10000);
}
